### ISSUE TITLE
Corrupted .CSV file

### ISSUE THREAD

**Issue by nvhuy** [ilija139/PDTB-Parser#1]
The .CSV file has last rows contain only "." instead of the actual words. This file is important because it stores the absolute offset of every single words in the text. I use this information to align the parser output with our annotated sentences. One sample input file is attached. You can run the parser and check the output .csv file.

[2014_Koury_P1D1 - chase-green-67.txt](https://github.com/ilija139/PDTB-Parser/files/41131/2014_Koury_P1D1.-.chase-green-67.txt)

**Comment by ilija139** [comment]
As we discussed, please check the text file for special or unusual characters around the last correctly recognized word. 

Please open this issue in the official repo https://github.com/WING-NUS/pdtb-parser as I'm no longer maintaining this.
